USE sakila;

-- 1. List the number of films per category.

SELECT c.name, COUNT(f.film_id) AS films_category
FROM film AS f
	INNER JOIN film_category AS fc
		ON f.film_id = fc.film_id
	INNER JOIN category AS c
		ON fc.category_id = c.category_id
GROUP BY c.name;

-- 2. Retrieve the store ID, city, and country for each store.

SELECT st.store_id, ci.city, co.country
FROM store AS st
	INNER JOIN address AS ad
		ON st.address_id = ad.address_id
	INNER JOIN city AS ci
		ON ci.city_id = ad.city_id
	INNER JOIN country AS co
		ON co.country_id = ci.country_id;
        
-- 3.  Calculate the total revenue generated by each store in dollars.

SELECT sto.store_id, SUM(amount) AS total_revenue
FROM payment AS pay
	INNER JOIN staff AS sta
		ON sta.staff_id = pay.staff_id
	INNER JOIN store AS sto
		ON sto.manager_staff_id = sta.staff_id
GROUP BY sto.store_id;

-- 4.  Determine the average running time of films for each category.

SELECT cat.name, AVG(f.length) AS avg_length
FROM category AS cat
	INNER JOIN film_category AS fc
		ON fc.category_id = cat.category_id
	INNER JOIN film AS f
		ON f.film_id = fc.film_id
GROUP BY cat.name;

-- 5.Identify the film categories with the longest average running time.

SELECT cat.name, AVG(f.length) AS avg_length
FROM category AS cat
	INNER JOIN film_category AS fc
		ON fc.category_id = cat.category_id
	INNER JOIN film AS f
		ON f.film_id = fc.film_id
GROUP BY cat.name
ORDER BY avg_length DESC
LIMIT 3;

-- 6.  Display the top 10 most frequently rented movies in descending order.
